; Landmarks indexes (see data/maps/landmarks.asm)
	const_def
	const LANDMARK_SPECIAL	
	const LANDMARK_NEPETA_GROVE
	const LANDMARK_MT_GOJI
	const LANDMARK_JUNIPER_CAVE
	const LANDMARK_GINSENG_TOWER
	const LANDMARK_GOLDENSEAL_CITY
	const LANDMARK_ROUTE_6
	const LANDMARK_PERSIMMON_CITY
	const LANDMARK_LYCOPUS_COPSE
	const LANDMARK_ROUTE_5
	const LANDMARK_WITCHHAZEL_WOODS
	const LANDMARK_HIBISCUS_CITY
	const LANDMARK_RAGWEED_SWAMP
	const LANDMARK_LIQUORICE_FALLS
	const LANDMARK_PASSIFLORA_TOWN
	const LANDMARK_ROUTE_4
	const LANDMARK_CAMPHOR_CAPE
	const LANDMARK_MAGNOLIA_ISLET
	const LANDMARK_ROUTE_3
	const LANDMARK_JACARANDA_TOWN
	const LANDMARK_VALERIAN_PASS
	const LANDMARK_MT_GINGER
	const LANDMARK_TAURIC_TOWN
	const LANDMARK_ROUTE_2
	const LANDMARK_CHAMOMILE_CITY
	const LANDMARK_BILBERRY_WOODS
	const LANDMARK_TARRAGON_TOWN
	const LANDMARK_ROUTE_1
	const LANDMARK_NEW_BARK  ; 01
        
DEF KANTO_LANDMARK EQU const_value
	const LANDMARK_PALLET_TOWN
	const LANDMARK_ROUTE_28
	const LANDMARK_VICTORY_ROAD
	const LANDMARK_INDIGO_PLATEAU    ; 20
	const LANDMARK_FAST_SHIP         ; 21
DEF NUM_LANDMARKS EQU const_value

; used in CaughtData
	const_def $7f, -1
	const LANDMARK_EVENT             ; $7f
	const LANDMARK_GIFT              ; $7e

; Regions
	const_def
	const JOHTO_REGION ; 0
	const KANTO_REGION ; 1
DEF NUM_REGIONS EQU const_value
